DELETE FROM DecoracaoCerimonial
DELETE FROM Evento
DELETE FROM FornecedorBoloDoceBemCasado
DELETE FROM Foto
DELETE FROM FotoVideo
DELETE FROM Gastronomia
DELETE FROM ItemBebida
DELETE FROM ItemBebidaSelecionado
DELETE FROM ItemBoloDoceBemCasado
DELETE FROM ItemBoloDoceBemCasadoEvento
DELETE FROM ItemBoloDoceBemCasadoSelecionado
DELETE FROM ItemCerimonial
DELETE FROM ItemDecoracao
DELETE FROM ItemDecoracaoCerimonial
DELETE FROM ItemDecoracaoCerimonialSelecionado
DELETE FROM ItemDecoracaoSelecionado
DELETE FROM ItemFotoVideo
DELETE FROM ItemFotoVideoSelecionado
DELETE FROM ItemMontagem
DELETE FROM ItemMontagemSelecionado
DELETE FROM ItemOutrosItens
DELETE FROM ItemOutrosItensSelecionado
DELETE FROM ItemRoteiro
DELETE FROM ItemSomIluminacao
DELETE FROM ItemSomIluminacaoSelecionado
DELETE FROM Local
DELETE FROM Modulo
DELETE FROM Montagem
DELETE FROM OutrosItens
DELETE FROM Perfil
DELETE FROM PerfilModulo
DELETE FROM Prato
DELETE FROM PratoCardapio
DELETE FROM PratoSelecionado
DELETE FROM Reuniao
DELETE FROM RoteiroPadrao
DELETE FROM SomIluminacao
DELETE FROM TipoItemBebida
DELETE FROM TipoItemBoloDoceBemCasado
DELETE FROM TipoItemDecoracao
DELETE FROM TipoItemDecoracaoCerimonial
DELETE FROM TipoItemFotoVideo
DELETE FROM TipoItemMontagem
DELETE FROM TipoItemOutrosItens
DELETE FROM TipoItemSomIluminacao
DELETE FROM TipoPrato
DELETE FROM TipoPratoPadrao
DELETE FROM TipoReuniao
DELETE FROM TipoServico
DELETE FROM Usuario
DELETE FROM Bebida
DELETE FROM BoloDoceBemCasado
DELETE FROM Cardapio
DELETE FROM CardapioPadrao
DELETE FROM ContratoAditivo
DELETE FROM Decoracao